[package]
name = "frontend"
version = "0.1.0"
edition = "2021"


[dependencies]
trunk = "0.20.3"
yew = { version = "0.21.0", features = ["csr"] }
yew-router = "0.18.0"
chrono = "0.4.38"
lazy_static = "=1.5.0"
palette = "0.7.6"
wasm-bindgen = "0.2.92"
web-sys = "0.3.69"
